import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Button from "../components/Button";
import Table from "../components/Table";

export type Dias = {
  id: string;
  name: string;
  created_at: Date;
};

const Home: NextPage = () => {
 
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <main className="mx-6 mt-8">
          <div className="flex justify-end">
            <Link href="/novo-treino" passHref>
              <a className="mb-8">
                <Button>Novo treino</Button>
              </a>
            </Link>
          </div>
          <section className="flex flex-col justify-center">
            <Table />
          </section>
        </main>
      </>
    </div>
  );
};

export default Home;
